"""empty message

Revision ID: fd287a7de0e2
Revises:
Create Date: 2025-02-14 15:04:52.289400

"""

import sqlalchemy as sa
from alembic import op
from app.models.fields import JsonField

# revision identifiers, used by Alembic.
revision = "fd287a7de0e2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("slug", sa.String(length=255), nullable=True),
        sa.Column(
            "ai_resource",
            sa.String(length=255),
            server_default="claude",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_processed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("original_data", JsonField(), nullable=True),
        sa.Column("processed_data", JsonField(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_processed")
    op.drop_table("company")
    # ### end Alembic commands ###
